### ISSUE TITLE
Week 6 - ready for review

### ISSUE THREAD

**Issue by klienert** [klienert/QuizBuilder#1]
@pawaitemadisoncollege week 6 is complete

<img width="1262" alt="Screenshot 2023-03-02 at 9 04 54 AM" src="https://user-images.githubusercontent.com/58708016/222466822-6efd6add-e82d-4087-9d3d-6b86bc40bcda.png">

<img width="1256" alt="Screenshot 2023-03-02 at 9 05 10 AM" src="https://user-images.githubusercontent.com/58708016/222466848-316e2154-5898-49f5-b28b-0b9979f2a942.png">

**Comment by pawaitemadisoncollege** [comment]
Wooohooo @klienert! Your indie project is OUT ON THE WEB!!! So cool!   Thanks for being on top of adding your deployed app link in the indie project list too.

I hope the coding group you proposed really takes off - there is so much power in collaborating as I think we saw in office hours this week.

Have a great weekend!
