### ISSUE TITLE
Peer Review 1 - Myo Min Han

### ISSUE THREAD

**Issue by Han434** [klienert/QuizBuilder#3]
Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|Problem Statement      |It describes the project purpose in a way that everyone understands.|It is simple and straight to the point. I think it can be improved by indicating what motivates the developer to create this project and including what teachers can do in this application in more detail.|
|Design Documentation   |Some documents are still to be completed.|Documents show the overall look of the application. I think it would be better to include which page the user is currently viewing. I think screen designs can use some improvement by adding descriptions of some information that will be available on a page.|
|Data model/Database    |Overall I think the model represents a powerful and well-thought database design.|I can see the effort of the developer creating this database. I think the user table can be improved by adding the userType field and I also think the answer field in the attempt_answer table is not necessary as it already existed in the answer field.|
|Code                   |To be completed.|Most of javabean are in place. I am not sure about the package structure though. Deleting placeholder files might be something the developer wants to do.|

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434 Thank you for your thoughtful review of @klienert's project. You have a good eye for the details and your comments help identify what is on target and what could be improved.

**Comment by Han434** [comment]
Yes, I did and everything seems to be alright with that topic.
